#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.0.4 on Sat Apr  2 20:01:43 2022
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class NuevaUnidadDialog(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: NuevaUnidadDialog.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.SetTitle("dialog")

        sizer = wx.BoxSizer(wx.VERTICAL)

        lblAdd = wx.StaticText(self, wx.ID_ANY, u"Añadir nueva unidad")
        lblAdd.SetToolTip(u"Unidad a escanear. Puedes seleccionar una carpeta utilizando el primer ítem de la lista (Añadir ubicación...)")
        sizer.Add(lblAdd, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 5)

        self.selUnidades = wx.ListCtrl(self, wx.ID_ANY, style=wx.LC_HRULES | wx.LC_REPORT | wx.LC_VRULES)
        self.selUnidades.AppendColumn("Unidades", format=wx.LIST_FORMAT_LEFT, width=-1)
        sizer.Add(self.selUnidades, 1, wx.ALL | wx.EXPAND, 5)

        box = wx.BoxSizer(wx.HORIZONTAL)
        sizer.Add(box, 0, wx.ALL | wx.EXPAND, 5)

        lblNombre = wx.StaticText(self, wx.ID_ANY, "Nombre:")
        box.Add(lblNombre, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 5)

        self.etiquetaUnidad = wx.TextCtrl(self, wx.ID_ANY, "")
        self.etiquetaUnidad.SetMinSize((80, -1))
        self.etiquetaUnidad.SetToolTip("Escribe el nombre/etiqueta de la unidad seleccionada")
        box.Add(self.etiquetaUnidad, 1, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 5)

        line1 = wx.StaticLine(self, wx.ID_ANY)
        sizer.Add(line1, 0, wx.ALL | wx.EXPAND, 5)

        self.chkunidades = wx.CheckBox(self, wx.ID_ANY, "Mostrar todas las unidades")
        self.chkunidades.SetToolTip(u"Actívalo para mostrar unidades de sistema u ocultas")
        sizer.Add(self.chkunidades, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 5)

        line2 = wx.StaticLine(self, wx.ID_ANY)
        sizer.Add(line2, 0, wx.ALL | wx.EXPAND, 5)

        btnSizer = wx.StdDialogButtonSizer()
        sizer.Add(btnSizer, 0, wx.ALL, 5)

        self.btnAnadir = wx.Button(self, wx.ID_APPLY, "")
        self.btnAnadir.Enable(False)
        self.btnAnadir.SetLabel("Añadir")
        btnSizer.AddButton(self.btnAnadir)

        self.btnCancelar = wx.Button(self, wx.ID_CANCEL, "")
        self.btnCancelar.SetLabel("Cancelar")
        btnSizer.AddButton(self.btnCancelar)

        btnSizer.Realize()

        self.SetSizer(sizer)
        sizer.Fit(self)

        self.Layout()
        # end wxGlade

# end of class NuevaUnidadDialog

class MyApp(wx.App):
    def OnInit(self):
        self.dialog = NuevaUnidadDialog(None, wx.ID_ANY, "")
        self.SetTopWindow(self.dialog)
        self.dialog.ShowModal()
        self.dialog.Destroy()
        return True

# end of class MyApp

if __name__ == "__main__":
    app = MyApp(0)
    app.MainLoop()
