#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.0.4 on Wed Mar 30 21:20:57 2022
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
import wx.lib.agw.hypertreelist as HTL
# end wxGlade


class indEXa(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: indEXa.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((800, 450))
        self.SetTitle("frame")

        # Menu Bar
        self.menubar = wx.MenuBar()
        wxglade_tmp_menu = wx.Menu()
        self.menubar.muestra_ocultos = wxglade_tmp_menu.Append(wx.ID_ANY, "&Mostrar archivos ocultos", "Muestra archivos de sistema que suelen estar ocultos", wx.ITEM_CHECK)
        self.menubar.Append(wxglade_tmp_menu, "&Opciones")
        self.SetMenuBar(self.menubar)
        # Menu Bar end

        self.barraestado = self.CreateStatusBar(1, wx.STB_ELLIPSIZE_MIDDLE | wx.STB_SHOW_TIPS)
        self.barraestado.SetStatusWidths([-1])
        # statusbar fields
        barraestado_fields = ["frame_statusbar"]
        for i in range(len(barraestado_fields)):
            self.barraestado.SetStatusText(barraestado_fields[i], i)

        self.pPrincipal = wx.Panel(self, wx.ID_ANY)

        primerDivisor = wx.BoxSizer(wx.HORIZONTAL)

        dUnidades = wx.BoxSizer(wx.VERTICAL)
        primerDivisor.Add(dUnidades, 2, wx.EXPAND, 0)

        self.eBuscar = wx.SearchCtrl(self.pPrincipal, wx.ID_ANY, "")
        self.eBuscar.SetToolTip(u"Escribe el texto a buscar y pulsa Intro para iniciar la búsqueda.")
        self.eBuscar.ShowCancelButton(True)
        dUnidades.Add(self.eBuscar, 0, wx.ALL | wx.EXPAND, 6)

        self.lUnidades = wx.ListCtrl(self.pPrincipal, wx.ID_ANY, style=wx.LC_HRULES | wx.LC_REPORT)
        self.lUnidades.AppendColumn("Unidades", format=wx.LIST_FORMAT_LEFT, width=-1)
        dUnidades.Add(self.lUnidades, 1, wx.ALL | wx.EXPAND, 6)

        sBotones = wx.BoxSizer(wx.HORIZONTAL)
        dUnidades.Add(sBotones, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 6)

        self.btnGestionar = wx.Button(self.pPrincipal, wx.ID_ANY, "Gestionar")
        self.btnGestionar.SetToolTip(u"Muestra la herramienta para añadir unidades a la base de datos.")
        sBotones.Add(self.btnGestionar, 1, wx.ALL | wx.EXPAND, 3)

        self.btnDuplicados = wx.Button(self.pPrincipal, wx.ID_ANY, "Duplicados")
        self.btnDuplicados.SetToolTip("Busca archivos duplicados mayores de 100 megas.")
        sBotones.Add(self.btnDuplicados, 1, wx.ALL | wx.EXPAND, 3)

        dArbol = wx.BoxSizer(wx.VERTICAL)
        primerDivisor.Add(dArbol, 7, wx.EXPAND, 0)

        self.tArbol = HTL.HyperTreeList(self.pPrincipal, agwStyle=wx.TR_DEFAULT_STYLE | HTL.TR_ELLIPSIZE_LONG_ITEMS)
        colorfondo = wx.SystemSettings.GetColour(wx.SYS_COLOUR_LISTBOX)
        self.tArbol.SetBackgroundColour(colorfondo)
        self.tArbol.AddColumn("Nombre")
        self.tArbol.AddColumn("Tamaño")
        self.tArbol.SetMainColumn(0) # the one with the tree in it...
        self.tArbol.SetColumnWidth(0, 400)
        dArbol.Add(self.tArbol, 1, wx.ALL | wx.EXPAND, 6)

        self.lArbol = wx.ListCtrl(self.pPrincipal, wx.ID_ANY, style=wx.LC_HRULES | wx.LC_REPORT | wx.LC_VRULES)
        self.lArbol.Hide()
        self.lArbol.AppendColumn("Archivo", format=wx.LIST_FORMAT_LEFT, width=380)
        self.lArbol.AppendColumn(u"Tamaño", format=wx.LIST_FORMAT_LEFT, width=80)
        self.lArbol.AppendColumn("Unidad", format=wx.LIST_FORMAT_LEFT, width=90)
        self.lArbol.AppendColumn("Ruta", format=wx.LIST_FORMAT_LEFT, width=0)
        dArbol.Add(self.lArbol, 1, wx.ALL | wx.EXPAND, 6)

        self.pPrincipal.SetSizer(primerDivisor)

        self.Layout()
        # end wxGlade

# end of class indEXa

class MyApp(wx.App):
    def OnInit(self):
        self.frame = indEXa(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

# end of class MyApp

if __name__ == "__main__":
    app = MyApp(0)
    app.MainLoop()
